name: attendance_app
description: 部活動出欠管理アプリ
publish_to: 'none'
version: 1.9.0+25

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  dio: ^5.4.3

  # フォント
  google_fonts: ^6.2.1

  # 状態管理
  provider: ^6.1.2

  # トークン安全保存
  flutter_secure_storage: ^9.2.2

  # カレンダー
  table_calendar: ^3.1.2

  # 日付フォーマット
  intl: ^0.19.0

  # キャッシュ
  shared_preferences: ^2.3.3

  # UI アイコン
  cupertino_icons: ^1.0.8

  # OTA アップデート
  package_info_plus: ^9.0.1
  path_provider: ^2.1.0
  open_filex: ^4.5.0

  # URL 起動 (iOS: TestFlight 誘導)
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
